language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pep8
before_script:
  - "pep8 --exclude=urls.py --ignore=E501 ."
  - pyflakes .
script: nosetests
